---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitops-service-mongodb
  namespace: gitops-service
spec:
  releaseName: gitops-service-mongodb
  interval: 10m
  chart:
    spec:
      chart: mongodb
      version: "14.3.2"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: gitops-service
  values:
    architecture: "standalone"
    auth:
      rootUser: "root"
      rootPassword: "root"
      enabled: true
    image:
      repository: zcube/bitnami-compat-mongodb # this is for arm64, patch to override (Mac M1 and M2)
      digest: sha256:3a22ea59dc7a66007adf27ab71f1bbe754a992b6487a4a94d640e8ac2a406cef # this is for arm64, patch to override (Mac M1 and M2)
    persistence:
      enabled: false
    readinessProbe:
      failureThreshold: 6
      initialDelaySeconds: 30
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5