---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitops-observability-backend-chart
spec:
  releaseName: gitops-observability-backend
  interval: 10m
  chart:
    spec:
      chart: gitops-observability-backend-chart
      version: "0.0.1"
      sourceRef:
        kind: HelmRepository
        name: gitops-observability-backend-chart
        namespace: gitops-service
  values:
    imagePullSecrets:
      - name: gcr-docker-registry
    image:
      repository: gcr.io/malike/gitops-backend-service
      tag: latest
    configMap: environment-configmap
    nodeSelector:
      node.kubernetes.io/role: platform
      kubernetes.io/os: linux
